name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  NODE_ENV: ${{vars.NODE_ENV}}
  PORT: ${{vars.PORT}}
  DB: ${{secrets.DB}}
  GOOGLE_CLIENT_ID: ${{secrets.GOOGLE_CLIENT_ID}}
  GOOGLE_CLIENT_SECRET: ${{secrets.GOOGLE_CLIENT_SECRET}}
  GOOGLE_HD_ALLOWED_DOMAINS: ${{secrets.GOOGLE_HD_ALLOWED_DOMAINS}}
  CLIENTS: ${{secrets.CLIENTS}}
  AUDIENCES: ${{vars.AUDIENCES}}
  ISSUER: ${{vars.ISSUER}}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test --coverage
